# Generated by Django 5.0.6 on 2026-09-10 17:20

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='id_number',
            field=apps.core.fields.EncryptedCharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='payvessel_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
