# Generated by Django 5.0.6 on 2026-09-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'permissions': [('can_approve_members', 'Can approve pending member registrations')]},
        ),
    ]
