# Generated by Django 5.0.6 on 2026-09-05 10:21

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_memberprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='id_number',
            field=apps.core.fields.EncryptedCharField(max_length=120),
        ),
    ]
