# Generated by Django 5.0.6 on 2026-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_memberprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='payvessel_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='payvessel_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
