# Generated by Django 5.0.6 on 2026-09-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_reports', 'Can view and download bulk reports (member statements, loan book, overdue list)')]},
        ),
    ]
