# Generated by Django 5.0.6 on 2026-09-03 15:47

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='payvessel', max_length=20)),
                ('transaction_reference', models.CharField(db_index=True, max_length=150, unique=True)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('rejected_signature', 'Rejected — Invalid Signature'), ('rejected_ip', 'Rejected — IP Not Allowlisted'), ('rejected_unmatched', 'Rejected — No Member Found for Account'), ('duplicate', 'Duplicate — Already Processed')], max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('resulting_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.ledgerentry')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.payments.models.receipt_upload_path)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('claimed_type', models.CharField(choices=[('deposit', 'Savings Deposit'), ('share_capital_contribution', 'Share Capital Contribution')], max_length=32)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('possible_duplicate', 'Possible Duplicate'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('resulting_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.ledgerentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_c78898_idx')],
            },
        ),
    ]
