# Generated by Django 5.0.6 on 2026-09-04 09:58

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to=apps.payments.models.reconciliation_upload_path)),
                ('total_rows_in_file', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('discrepancy_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('amount_mismatch', 'Amount Mismatch'), ('missing_locally', 'In PayVessel File, Not Found Locally'), ('missing_in_file', 'Processed Locally, Not Found in PayVessel File')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=150)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.webhookevent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='payments.reconciliationrun')),
            ],
            options={
                'ordering': ['kind', 'transaction_reference'],
            },
        ),
    ]
