# Generated by Django 5.0.6 on 2026-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_reconciliationrun_reconciliationdiscrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='claimed_type',
            field=models.CharField(choices=[('deposit', 'Savings Deposit'), ('share_capital_contribution', 'Share Capital Contribution')], max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
