# Generated by Django 5.0.6 on 2026-09-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at'], 'permissions': [('can_record_manual_transaction', 'Can record manual transactions and loan repayments (Treasurer-level)'), ('can_view_ledger_exports', 'Can view and download weekly ledger exports')]},
        ),
    ]
