# Generated by Django 5.0.6 on 2026-09-03 15:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEligibilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_tenure_months', models.PositiveIntegerField()),
                ('min_savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('max_loan_multiple', models.DecimalField(decimal_places=2, help_text="Loan amount is capped at this many times the member's current savings balance.", max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tiers are hidden from new applications but existing loans keep referencing them.')),
            ],
            options={
                'verbose_name_plural': 'Loan eligibility policies',
                'ordering': ['min_tenure_months'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('financing_structure', models.CharField(choices=[('qard_hasan', 'Qard Hasan (interest-free)'), ('murabaha', 'Murabaha (fixed profit margin)')], max_length=20)),
                ('murabaha_profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tenure_months', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('guarantor_pending', 'Awaiting Guarantor'), ('approved', 'Approved — Awaiting Disbursement'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('guarantor_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('guarantor_declined_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loaneligibilitypolicy')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['status', 'due_date'], name='loans_repay_status_eb8bd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan', 'installment_number')},
        ),
    ]
