# Generated by Django 5.0.6 on 2026-09-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-applied_at'], 'permissions': [('can_review_loans', 'Can approve, reject, and disburse loan applications (Chairman-level)')]},
        ),
    ]
