# Generated by Django 5.0.6 on 2026-09-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='financing_structure',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='murabaha_profit_amount',
        ),
    ]
